# Generated by Django 5.1 on 2024-09-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_deleted_for_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_for_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
